# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: myPassword

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
  http:
    multipart:
      max-file-size: 100KB
      max-request-size: 100KB
