# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/input_numbers
    username: postgres
    password: myPassword
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      ddl-auto: create-drop