name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      # Setting up the Java environment
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: 'maven'

      - name: Cache the Gradle packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Gradle
        run: gradle build
